/* LLMOSAFE: Safety-Critical AI Agent Library (C Bindings) */

#ifndef LLMOSAFE_H
#define LLMOSAFE_H

#pragma once

/* This file is automatically generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Synapse Synapse;

#define STABILITY_THRESHOLD 1000

#define PRESSURE_THRESHOLD 800

/**
 * C-ABI entry point for environmental entropy.
 */
uint16_t llmosafe_get_environmental_entropy(void);

int32_t llmosafe_process_synapse(uint64_t synapse_bits);

uint16_t llmosafe_calculate_halo(const uint8_t *text_ptr, size_t text_len);

int32_t llmosafe_check_resources(uint32_t ceiling_mb);

uint8_t llmosafe_get_resource_pressure(uint32_t ceiling_mb);

int32_t llmosafe_get_stability(uint64_t synapse_bits);

uint8_t llmosafe_get_system_cpu_load(void);

#endif /* LLMOSAFE_H */
